### ISSUE TITLE
爬一会就403了

### ISSUE THREAD

**Issue by qq1693129601** [lanbing510/DouBanSpider#1]
403 Forbidden

nginx

**Comment by lanbing510** [comment]
嗯嗯 我今天爬更多的数据的时候也遇到了 之前爬的很Easy。。。
1 已经添加用User Agent模仿浏览器行为来爬，同时加入了间隔随机时间，可以很大程度上避免豆瓣检测为爬虫并封锁~
2 亲，爬的不要太快就没问题了，最新代码已测，已爬完~

最后再出现问题的话，再就是代理IP了，爬虫，没办法。。。

**Comment by lanbing510** [comment]
在就是建议晚上爬，上次我是半夜爬的，爬的间隔时间也很短（300ms），也没用User Agent，奇迹般的完全爬完了
