### ISSUE TITLE
通过标签分页不能抓取大于1000本的图书信息

### ISSUE THREAD

**Issue by blurm** [lanbing510/DouBanSpider#10]
比如：
[https://book.douban.com/tag/%E5%B0%8F%E8%AF%B4?start=1099&type=T](https://book.douban.com/tag/%E5%B0%8F%E8%AF%B4?start=1099&type=T)
返回`没有找到符合条件的图书`

**Comment by SimonCqk** [comment]
试试这个：
https://github.com/SimonCqk/DouBanCrawls
改进了一下

**Comment by blurm** [comment]
@SimonCqk 你有最近运行过么？通过tag的分页链接只能取到前50页，大于50页就不返回内容了。不太清楚是不是一直这样。

**Comment by SimonCqk** [comment]
27行
```
 page_num*15
```
改成
```
page_num*20
```
试试  豆瓣好像改网页结构了

**Comment by blurm** [comment]
@SimonCqk 不管是20还是15，start >= 1000就不再返回内容了

**Comment by lanbing510** [comment]
豆瓣已经更改了网页结构。

**Comment by Bryce-JM** [comment]
请问现在页码可以爬取超过50页吗
