### ISSUE TITLE
我用的是python 3.6版本

### ISSUE THREAD

**Issue by wuwufeiwu** [lanbing510/DouBanSpider#12]
wb=Workbook(optimized_write = True)
这个地方提示出错，是由于版本不对吗，你用的是哪个版本

**Comment by lanbing510** [comment]
2.7

**Comment by lanbing510** [comment]
2.7

**Comment by xoyabc** [comment]
@wuwufeiwu 
因为openpyxl 2.4.0-a1 (2016-04-11)版本以上已经移除了optimized_write参数，
可以参考[typeerror-init-got-an-unexpected-keyword-argument-optimized-write](https://stackoverflow.com/questions/45073053/typeerror-init-got-an-unexpected-keyword-argument-optimized-write)，将110行的`wb=Workbook(optimized_write=True)`改为`Workbook(write_only = True)`即可。
