### ISSUE TITLE
菜鸟请教

### ISSUE THREAD

**Issue by woodzeng** [lanbing510/DouBanSpider#3]
请问交互界面代码能放出吗?还有，我运行了代码，只能爬到1个excel，是什么原因呢？

**Comment by lanbing510** [comment]
还没服务器，暂时是放不出来了，等有钱了买个服务器玩，然后再免费放出来。最新版的代码没有公开，这里的代码已经过时了。

**Comment by woodzeng** [comment]
好吧，还是多谢啦~
