### ISSUE TITLE
tag list

### ISSUE THREAD

**Issue by DaoQiu** [lanbing510/DouBanSpider#4]
请问，关于书的标签您是怎么取到的？我在豆瓣读书的网页下发现，很多标签都没有展现出来，但是您的代码中有很多比较细的标签。（不知道在哪能私信到您，只能在issue里边发问。希望没有打扰到您）

**Comment by lanbing510** [comment]
以前代码的标签是自己选的感兴趣的主题词汇，并非爬下来的。

**Comment by DaoQiu** [comment]
好的，谢谢您的回复。
