### ISSUE TITLE
爬完整个豆瓣大概用了多长时间？

### ISSUE THREAD

**Issue by yuzhounh** [lanbing510/DouBanSpider#5]
请问一下，你的代码爬完整个豆瓣大概用了多长时间？

另外，豆瓣所有的图书信息（3088633本，2138386KB），大概2GB，能不能分享一下，比如百度云盘？我想结合这些数据多找些高分的书看看。谢谢！

**Comment by woodzeng** [comment]
同求~

**Comment by lanbing510** [comment]
爬了好像两三个星期，时间过去一段了，记不太清了。抱歉数据暂时不能公开，公开可能涉及豆瓣版权问题，谢谢！

**Comment by yuzhounh** [comment]
Anyway，还是非常感谢你的回复，谢谢！

**Comment by buluzhai** [comment]
看豆瓣的分类浏览标签“小说”的有4184075种，应该是爬的不全？

**Comment by AddASecond** [comment]
真的好慢啊。。。不知道能不能想办法更快一些？

**Comment by songlin51** [comment]
能问一下，爬取的时候，豆瓣防机器人验证码怎么绕过的吗

**Comment by idreamboat** [comment]
你好 ？你是？从哪儿看到我的gamil的？

发自我的 iPhone

**Comment by lanbing510** [comment]
对于防机器人验证码，只要你爬的不是特别快一般不会出现，可以对爬取不成功的页面进行了记录，然后爬完一遍对爬取不成功的进行爬取，直到全部成功。

**Comment by lanbing510** [comment]
现在公开的是最最初的版本，不是爬全的版本，爬全部的版本和数据暂时都没公开，等有时间了整理后公开。

**Comment by ruiq** [comment]
现在能公开了吗😂

**Comment by yisheng124** [comment]
> 

现在能公开了吗？
