### ISSUE TITLE
unexpected keyword argument 'optimized_write'

### ISSUE THREAD

**Issue by LyciaP** [lanbing510/DouBanSpider#7]
在运行到110行wb=Workbook(optimized_write=True)的时候，报这个错：
TypeError: __init__() got an unexpected keyword argument 'optimized_write'

Mac book, python 2.7.13

改成wb=Workbook()，问题解决。

请问optimized_write=True的作用是什么？删掉有影响吗？

**Comment by linxidd** [comment]
>2.4.0-a1 (2016-04-11)
>Removed optimized_write keyword for new workbooks. Use write_only instead.
同样的问题，因为openpyxl新版本移除了这个属性。删除这个选项就好。具体的还没细看，因为我没用建新表的功能。

**Comment by Jerry-Moo** [comment]
我发现，程序是运行完成才生成 .xlsx文件，如果爬取的资料太多，会不会把内存跑光？

**Comment by lanbing510** [comment]
会的，但现在公开的这个程序爬不了太多，只当做示例程序看看就好。爬取豆瓣全部数据的程序暂时没公开，用数据库进行的存储。
